from pptx import Presentation
from pptx.util import Inches, Pt
import io

def generate_pptx(slide_data: list, watermark: bool = False) -> bytes:
    """
    Generates a PPTX file from a list of slide dictionaries.
    Each dictionary should have 'title' and 'content' keys.
    """
    prs = Presentation()

    for slide_info in slide_data:
        title_text = slide_info.get("title", "Untitled")
        
        # Determine content. Can be 'content' or 'points' (list)
        content_raw = slide_info.get("content", "")
        points = slide_info.get("points", [])
        
        if isinstance(points, list) and points:
            # Join list into bullet points if provided as logic
            content_text = "\n".join(points)
        else:
            content_text = str(content_raw)

        # Use the Bullet Layout (typically index 1)
        # 0 = Title Slide, 1 = Title and Content
        slide_layout = prs.slide_layouts[1]
        slide = prs.slides.add_slide(slide_layout)

        # Set Title
        title = slide.shapes.title
        if title:
            title.text = title_text

        # Set Content
        if len(slide.placeholders) > 1:
            body_shape = slide.placeholders[1]
            tf = body_shape.text_frame
            tf.text = content_text
            
    if watermark:
        # Add a final slide or footer with watermark
        # Attempting footer on Master or just separate slide for simplicity
        # Simple approach: Add text box to the first slide or every slide? 
        # Ideally, master slide edit, but simplest is hardcoded text box on last slide.
        
        # Let's add a dedicated "Created with" slide at the end
        blank_layout = prs.slide_layouts[6] # Blank
        slide = prs.slides.add_slide(blank_layout)
        txBox = slide.shapes.add_textbox(Inches(1), Inches(3), Inches(8), Inches(1))
        tf = txBox.text_frame
        tf.text = "Generated by MODYFIRE"
        p = tf.paragraphs[0]
        p.font.size = Pt(24)
        p.font.bold = True
        p.alignment = 2 # CENTER (1=left, 2=center? PPTX enum is PP_ALIGN.CENTER)
        # Safe fallback if enum import is heavy: just text.

    output = io.BytesIO()
    prs.save(output)
    output.seek(0)
    return output.read()
