from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
import io

# Define Styling Constants
THEMES = {
    "default": {
        "bg_color": (255, 255, 255), # White
        "title_color": (0, 0, 0),    # Black
        "body_color": (80, 80, 80),  # Dark Grey
        "accent_color": (59, 130, 246) # Blue-500
    },
    "dark": {
        "bg_color": (15, 23, 42),    # Slate-900
        "title_color": (255, 255, 255),
        "body_color": (203, 213, 225), # Slate-300
        "accent_color": (139, 92, 246) # Violet-500
    },
    "corporate": {
        "bg_color": (255, 255, 255),
        "title_color": (30, 58, 138),  # Blue-900
        "body_color": (71, 85, 105),   # Slate-600
        "accent_color": (37, 99, 235)  # Blue-600
    },
    "warm": {
        "bg_color": (255, 251, 235),   # Amber-50
        "title_color": (120, 53, 15),  # Amber-900
        "body_color": (146, 64, 14),   # Amber-800
        "accent_color": (217, 119, 6)  # Amber-600
    }
}

def generate_pptx(slide_data: list, watermark: bool = False, theme_name: str = "default") -> bytes:
    """
    Generates a style-aware PPTX file interactively.
    """
    prs = Presentation()
    
    # Get Theme Colors
    theme = THEMES.get(theme_name, THEMES["default"])
    bg_rgb = RGBColor(*theme["bg_color"])
    title_rgb = RGBColor(*theme["title_color"])
    body_rgb = RGBColor(*theme["body_color"])
    
    # Pre-calculate layout indices
    # 0 = Title Slide (We use 1 for content mostly)
    # 6 = Blank (Good for custom layouts)
    
    for i, slide_info in enumerate(slide_data):
        title_text = slide_info.get("title", "Untitled")
        content_raw = slide_info.get("content", "")
        points = slide_info.get("points", [])
        
        if isinstance(points, list) and points:
             content_text = "\n".join(points)
        else:
             content_text = str(content_raw)

        # Create Slide
        slide_layout = prs.slide_layouts[1] # Title and Content
        slide = prs.slides.add_slide(slide_layout)
        
        # --- Apply Background ---
        background = slide.background
        fill = background.fill
        fill.solid()
        fill.fore_color.rgb = bg_rgb
        
        # --- Set Title ---
        title = slide.shapes.title
        if title:
            title.text = title_text
            # Style Title
            for paragraph in title.text_frame.paragraphs:
                paragraph.font.color.rgb = title_rgb
                paragraph.font.bold = True

        # --- Set Content ---
        if len(slide.placeholders) > 1:
            body_shape = slide.placeholders[1]
            tf = body_shape.text_frame
            tf.text = content_text
            
            # Style Content Paragraphs
            for paragraph in tf.paragraphs:
                paragraph.font.color.rgb = body_rgb
                paragraph.font.size = Pt(18)
                
    if watermark:
        # Add Watermark Slide
        blank_layout = prs.slide_layouts[6] 
        slide = prs.slides.add_slide(blank_layout)
        
        # Apply bg
        background = slide.background
        fill = background.fill
        fill.solid()
        fill.fore_color.rgb = bg_rgb
        
        txBox = slide.shapes.add_textbox(Inches(1), Inches(3), Inches(8), Inches(1))
        tf = txBox.text_frame
        tf.text = "Generated by MODYFIRE"
        p = tf.paragraphs[0]
        p.font.size = Pt(24)
        p.font.bold = True
        p.font.color.rgb = title_rgb # Use theme title color
        p.alignment = 2 # CENTER

    output = io.BytesIO()
    prs.save(output)
    output.seek(0)
    return output.read()
