import pytest
from httpx import AsyncClient, ASGITransport
from unittest.mock import AsyncMock, patch
from app.main import app
from app.models import User
from app.database import get_db
from app.routers.auth import get_replit_user

# Mock DB Session
async def override_get_db():
    mock_session = AsyncMock()
    yield mock_session

# Mock Users
async def mock_get_student_user():
    return User(id=1, email="student@test.com", tier="student", credits=5)

async def mock_get_prof_user():
    return User(id=2, email="prof@test.com", tier="professor", credits=100)

@pytest.mark.asyncio
async def test_watermark_free_trial():
    app.dependency_overrides[get_db] = override_get_db
    app.dependency_overrides[get_replit_user] = mock_get_student_user
    
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://localhost") as ac:
        response = await ac.post("/editor/export-pdf", json={"text": "Hello World"})
        
    assert response.status_code == 200
    # In FPDF2, output() usually returns bytearray or bytes
    assert b"Generated by Modifier" in response.content

@pytest.mark.asyncio
async def test_no_watermark_paid_tier():
    app.dependency_overrides[get_db] = override_get_db
    app.dependency_overrides[get_replit_user] = mock_get_prof_user
    
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://localhost") as ac:
        response = await ac.post("/editor/export-pdf", json={"text": "Hello World"})
        
    assert response.status_code == 200
    assert b"Generated by Modifier" not in response.content

    # Clear overrides
    app.dependency_overrides = {}
