from fastapi import APIRouter, HTTPException, Response, Depends
from pydantic import BaseModel
from fpdf import FPDF
import io
import google.generativeai as genai
from app.config import settings
from app.services.pptx_engine import generate_pptx, THEMES
from app.services.gemini_engine import convert_text_to_slides_json
from app.routers.auth import get_replit_user
import json

router = APIRouter()

class RewriteRequest(BaseModel):
    text: str
    tone: str

class PPTXRequest(BaseModel):
    text: str
    theme: str = "default"
    aspect_ratio: str = "16:9" # "16:9" or "1:1"
    writing_style: str = "neutral"

# ...

@router.post("/export-slides-pdf")
async def generate_user_slides_pdf(
    request: PPTXRequest, 
    user = Depends(get_replit_user)
):
    try:
        # 1. Get Slides
        json_str = await convert_text_to_slides_json(
            request.text, 
            count=10, 
            tone=request.writing_style
        )
        try:
            slide_data = json.loads(json_str)
        except:
             slide_data = [{"title": "Study Notes", "content": request.text}]

        # 2. Setup PDF (Landscape for 16:9, or Square)
        if request.aspect_ratio == "1:1":
            pdf = FPDF(orientation='P', unit='mm', format=(200, 200))
            width, height = 200, 200
        else:
            pdf = FPDF(orientation='L', unit='mm', format='A4')
            width, height = 297, 210

        # 3. Get Theme Colors
        theme = THEMES.get(request.theme, THEMES["default"])
        bg = theme["bg_color"]
        title_c = theme["title_color"]
        body_c = theme["body_color"]

        pdf.set_auto_page_break(auto=False)

        for slide in slide_data:
            pdf.add_page()
            
            # Background
            pdf.set_fill_color(*bg)
            pdf.rect(0, 0, width, height, 'F')
            
            # Title
            pdf.set_font("Helvetica", "B", 28) # Larger Title
            pdf.set_text_color(*title_c)
            pdf.set_xy(20, 20)
            pdf.multi_cell(width-40, 14, slide.get("title", "Untitled"), align='L')
            
            # Divide Line (Optional visual separation)
            # pdf.set_draw_color(*title_c)
            # pdf.line(20, pdf.get_y()+5, width-20, pdf.get_y()+5)

            # Content (Points)
            pdf.set_font("Helvetica", "", 18)
            pdf.set_text_color(*body_c)
            # Dynamic Y positioning
            current_y = pdf.get_y() + 15
            pdf.set_y(current_y)
            
            points = slide.get("points", [])
            content_text = slide.get("content", "")
            
            if points and isinstance(points, list):
                for p in points:
                    pdf.set_x(25) # Indent
                    # Use simple dash for compatibility or try encoding
                    # using - as bullet for reliability
                    pdf.multi_cell(width-50, 10, f"-  {p}")
                    pdf.ln(5) # Add spacing between points
            else:
                pdf.set_x(25)
                pdf.multi_cell(width-50, 10, str(content_text))

        # Watermark
        if not user or (user.tier == "student" and user.credits <= 1):
             pdf.add_page()
             pdf.set_fill_color(*bg)
             pdf.rect(0, 0, width, height, 'F')
             pdf.set_font("Helvetica", "B", 30)
             pdf.set_text_color(*title_c)
             pdf.set_xy(0, height/2 - 10)
             pdf.cell(width, 20, "Generated by MODYFIRE", align='C')

        pdf_bytes = pdf.output()
        
        return Response(
            content=bytes(pdf_bytes),
            headers={"Content-Disposition": "attachment; filename='study_slides.pdf'"},
            media_type="application/pdf"
        )

    except Exception as e:
        print(f"PDF Slides Error: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/export-pptx")
async def generate_user_pptx(
    request: PPTXRequest, 
    user = Depends(get_replit_user)
):
    try:
        # 1. Convert text to JSON Structure via Gemini
        json_str = await convert_text_to_slides_json(
            request.text, 
            count=10, 
            tone=request.writing_style
        )
        
        # 2. Parse JSON
        try:
            slide_data = json.loads(json_str)
        except json.JSONDecodeError:
            slide_data = [{"title": "Study Notes", "content": request.text}]
            
        # 3. Check Watermark Condition
        should_watermark = False
        if not user or (user.tier == "student" and user.credits <= 1):
            should_watermark = True

        # 4. Generate PPTX
        pptx_bytes = generate_pptx(
            slide_data, 
            watermark=should_watermark, 
            theme_name=request.theme,
            aspect_ratio=request.aspect_ratio
        )
        
        return Response(
            content=pptx_bytes,
            headers={"Content-Disposition": "attachment; filename='study_notes.pptx'"},
            media_type="application/vnd.openxmlformats-officedocument.presentationml.presentation"
        )
    except Exception as e:
        print(f"PPTX Gen Error: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/rewrite")
async def rewrite_text(request: RewriteRequest):
    try:
        model = genai.GenerativeModel("gemini-1.5-flash")
        prompt = f"Rewrite the following text to be {request.tone}. Keep the meaning the same but adjust the style.\n\nText: {request.text}"
        
        response = model.generate_content(prompt)
        return {"rewritten_text": response.text}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

